pipeline {
    agent any

    parameters {
        string(name: 'inventory', defaultValue: 'dev', description: 'Environment to deploy to')
    }

    stages {
        stage('Initial cleanup') {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'main',
                url: 'https://github.com/<your-username>/ansible-config-mgt.git'
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh 'echo ${WORKSPACE}'
                sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
            }
        }

        stage('Run Ansible playbook') {
            steps {
                ansiblePlaybook(
                    become: true,
                    credentialsId: 'private-key',
                    disableHostKeyChecking: true,
                    installation: 'ansible',
                    inventory: 'inventory/${inventory}',
                    playbook: 'playbooks/site.yml'
                )
            }
        }

        stage('Clean Workspace after build') {
            steps {
                cleanWs(cleanWhenAborted: true,
                        cleanWhenFailure: true,
                        cleanWhenNotBuilt: true,
                        cleanWhenUnstable: true,
                        deleteDirs: true)
            }
        }
    }
}




